# Neural network module

**Подключим библиотеки и создадим модель нейросети с помощью фреймворка tensorflow**

In [113]:
import numpy as np
import tensorflow as tf
import pandas as pd
import csv
from tensorflow.keras.datasets import mnist

def create_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(117, activation='relu'),
        tf.keras.layers.Dense(117, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    return model


model = create_model()

**Загрузим граф связей и уберем индивидуальные номера агентов**

In [114]:
matrix_np = np.genfromtxt('matrix.csv', delimiter=';', dtype=str)

first_column = matrix_np[:, 0]
matrix_np = matrix_np[:, 1:]


first_row = matrix_np[0]
matrix_np = matrix_np[1:, :]
matrix_np = np.array(matrix_np, dtype=float)

**Выгрузим веса нейронной сети**

In [115]:
weights = model.get_weights()

In [116]:
weights

[array([[ 0.05484433,  0.0456527 ,  0.07181188, ..., -0.07716963,
         -0.01874546, -0.07272219],
        [-0.06742979,  0.06026493, -0.03481499, ..., -0.07238539,
         -0.06930083, -0.0659451 ],
        [ 0.04617852, -0.04381693, -0.02412068, ..., -0.0082428 ,
          0.05306518, -0.01036366],
        ...,
        [-0.02722652,  0.06960933, -0.00119185, ..., -0.00143982,
          0.03527859,  0.02962894],
        [ 0.03348115, -0.00026061,  0.01867969, ...,  0.00274567,
         -0.03884159,  0.03442681],
        [-0.01170427, -0.0421801 , -0.00545777, ..., -0.01719164,
          0.02835767,  0.01623394]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

**Загрузим граф связей в качестве весов между 2 скрытыми слоями и посмотрим на обновленные веса**

In [117]:
weights = matrix_np

model.layers[2].set_weights([weights, np.zeros(117, dtype=np.float32)])


model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [118]:
weights = model.get_weights()
weights

[array([[ 0.05484433,  0.0456527 ,  0.07181188, ..., -0.07716963,
         -0.01874546, -0.07272219],
        [-0.06742979,  0.06026493, -0.03481499, ..., -0.07238539,
         -0.06930083, -0.0659451 ],
        [ 0.04617852, -0.04381693, -0.02412068, ..., -0.0082428 ,
          0.05306518, -0.01036366],
        ...,
        [-0.02722652,  0.06960933, -0.00119185, ..., -0.00143982,
          0.03527859,  0.02962894],
        [ 0.03348115, -0.00026061,  0.01867969, ...,  0.00274567,
         -0.03884159,  0.03442681],
        [-0.01170427, -0.0421801 , -0.00545777, ..., -0.01719164,
          0.02835767,  0.01623394]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

**Обучим модель с нашими весами и посмотрим на результат**

In [119]:

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


train_images = train_images / 255.0
test_images = test_images / 255.0

model.fit(train_images, train_labels, epochs=5, batch_size=32, validation_data=(test_images, test_labels))

test_loss, test_accuracy = model.evaluate(test_images, test_labels)
print('Test loss:', test_loss)
print('Test accuracy:', test_accuracy)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2297 - accuracy: 0.9319 - val_loss: 0.1152 - val_accuracy: 0.9648
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1001 - accuracy: 0.9690 - val_loss: 0.0914 - val_accuracy: 0.9717
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0691 - accuracy: 0.9782 - val_loss: 0.0996 - val_accuracy: 0.9700
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0542 - accuracy: 0.9828 - val_loss: 0.0904 - val_accuracy: 0.9736
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0882 - accuracy: 0.9744
Test loss: 0.08816118538379669
Test accuracy: 0.974399983882904


In [120]:
weights = model.get_weights()
weights

[array([[ 0.05484433,  0.0456527 ,  0.07181188, ..., -0.07716963,
         -0.01874546, -0.07272219],
        [-0.06742979,  0.06026493, -0.03481499, ..., -0.07238539,
         -0.06930083, -0.0659451 ],
        [ 0.04617852, -0.04381693, -0.02412068, ..., -0.0082428 ,
          0.05306518, -0.01036366],
        ...,
        [-0.02722652,  0.06960933, -0.00119185, ..., -0.00143982,
          0.03527859,  0.02962894],
        [ 0.03348115, -0.00026061,  0.01867969, ...,  0.00274567,
         -0.03884159,  0.03442681],
        [-0.01170427, -0.0421801 , -0.00545777, ..., -0.01719164,
          0.02835767,  0.01623394]], dtype=float32),
 array([-0.01252074, -0.00083633,  0.05282348, -0.08583482,  0.04318917,
         0.00417375,  0.04101003, -0.04480871,  0.06994408, -0.03909237,
         0.102182  ,  0.03832491,  0.06233877,  0.0211111 , -0.02502985,
         0.10217434,  0.09407147,  0.06688452, -0.02377501, -0.01913572,
        -0.06024082, -0.04656536, -0.05528095, -0.00684424,  0.148

**Выгрузим обновленные веса и сохраним их**

In [121]:
df = weights[2]

matrix_np = df

matrix_np = np.array(matrix_np, dtype=str)

In [122]:
matrix_np

array([['0.10468649', '-0.081670746', '0.07344901', ..., '0.05557896',
        '0.1338575', '0.22942078'],
       ['0.014354382', '-0.041609667', '-0.041388635', ...,
        '-0.05875911', '0.0016989338', '0.062198486'],
       ['-0.0047302768', '0.041193943', '0.027188689', ...,
        '-0.24316633', '0.08096191', '0.07260458'],
       ...,
       ['0.097066596', '-0.1734803', '0.00029152347', ...,
        '-0.026333898', '-0.15347934', '0.0036753858'],
       ['0.07549351', '-0.1654294', '0.00022288229', ..., '-0.06765888',
        '-0.057191283', '0.24299942'],
       ['-0.09294891', '0.03210008', '0.09181444', ..., '0.107773',
        '-0.022766842', '-0.14284895']], dtype='<U32')

In [123]:
matrix_np = np.insert(matrix_np, 0, first_row, axis=0)
matrix_np = np.insert(matrix_np, 0, first_column, axis=1)

In [124]:
with open('modified_matrix.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile, delimiter=';')
    writer.writerows(matrix_np)

**Теперь можно адаптировать наш граф связей под приложение gelphi. Для этого запустите следующую ячейку**

In [128]:
import pandas as pd


matrix = pd.read_csv('/content/modified_matrix.csv', sep = ';', header=None)


source = []
target = []
weight = []
color = []
type_ = []

for i in range(1, 118):
    source.append(matrix.iloc[i, 0])
    target.append(matrix.iloc[i, 0])
    weight.append(1)
    color.append(0)
    type_.append('undirected')

    for j in range(1, 118):
        if i != j:
            current_color = matrix.iloc[i, j]
            if current_color >= 0.3:
                source.append(matrix.iloc[i, 0])
                target.append(matrix.iloc[0, j])
                weight.append(1)
                color.append(current_color)
                type_.append('undirected')

data = {
    'Source': source,
    'Target': target,
    'Weight': weight,
    'Color': color,
    'Type': type_
}
table = pd.DataFrame(data)
table['Target'] = table['Target'].astype(int)


table.to_csv('Weights.csv', sep=';', index=False)

FileNotFoundError: ignored